# fly.toml app configuration file generated for nwsbots on 2024-03-24T22:48:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwsbots'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="warnings"
  destination="/usr/local/lib/warnings"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
