# fly.toml app configuration file generated for nwsbots on 2024-03-23T23:24:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwsbots'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '8080'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
