name: Fly Deploy (radar)
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'
      - 'cmd/**'
      - 'bots/**'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only ./radar
        env:
          FLY_API_TOKEN: ${{ secrets.RADAR_FLY_API_TOKEN }}
